// src/cashfree.js
//
// Central place that touches the Cashfree Easy Split API. Two families of
// calls:
// - Standard Payment Gateway (orders): create an order, get its status.
// - Easy Split (vendors/splits): register a shop as a "vendor" with their
//   own bank account, then attach a split to an order so their share
//   settles straight to that account instead of sitting in this
//   platform's own Cashfree balance.
//
// IMPORTANT - built from Cashfree's public API documentation, not tested
// against a live sandbox (no real Cashfree credentials were available
// while writing this). Two things specifically worth confirming once real
// sandbox keys are in hand, before trusting this with real money:
//   1. Whether the split endpoint accepts an absolute "amount" (rupees)
//      per vendor, or only "percentage" - this file assumes "amount" is
//      supported (more precise for our tiered fee model, where the
//      platform's cut varies by order size rather than being a fixed %).
//      If only "percentage" is actually supported, createOrderSplit below
//      is the only place that needs to change.
//   2. The exact webhook signature algorithm (verifyWebhookSignature) -
//      built to match Cashfree's documented pattern (HMAC-SHA256 over
//      timestamp+rawBody, base64-encoded), but wasn't verifiable against
//      a real webhook delivery.
const crypto = require('crypto');
const {
  CASHFREE_CLIENT_ID,
  CASHFREE_CLIENT_SECRET,
  CASHFREE_ENV,
  CASHFREE_API_VERSION,
} = require('./config');

function getBaseUrl() {
  return CASHFREE_ENV === 'production' ? 'https://api.cashfree.com/pg' : 'https://sandbox.cashfree.com/pg';
}

function requireConfigured() {
  if (!CASHFREE_CLIENT_ID || !CASHFREE_CLIENT_SECRET) {
    // Fails the request that called this (via the route's try/catch), not
    // the whole server at boot - lets everything else keep working in an
    // environment where Cashfree just hasn't been set up yet.
    throw new Error('Cashfree is not configured - set CASHFREE_CLIENT_ID and CASHFREE_CLIENT_SECRET');
  }
}

function headers() {
  requireConfigured();
  return {
    'Content-Type': 'application/json',
    'x-api-version': CASHFREE_API_VERSION,
    'x-client-id': CASHFREE_CLIENT_ID,
    'x-client-secret': CASHFREE_CLIENT_SECRET,
  };
}

async function cashfreeRequest(method, path, body) {
  const res = await fetch(`${getBaseUrl()}${path}`, {
    method,
    headers: headers(),
    body: body ? JSON.stringify(body) : undefined,
  });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) {
    const message = data?.message || data?.error || `Cashfree API error (${res.status})`;
    const err = new Error(message);
    err.cashfreeStatus = res.status;
    err.cashfreeResponse = data;
    throw err;
  }
  return data;
}

// Creates a Cashfree order and returns a payment_session_id - the
// student's browser uses this with Cashfree's Checkout JS SDK to open the
// actual payment page. amount is always server-computed (see
// routes/jobs.js/batches.js), never taken from the client directly.
async function createOrder({ orderId, amount, customerPhone, returnUrl }) {
  return cashfreeRequest('POST', '/orders', {
    order_id: orderId,
    order_amount: amount,
    order_currency: 'INR',
    customer_details: {
      customer_id: `student_${customerPhone}`,
      customer_phone: customerPhone,
    },
    order_meta: {
      return_url: returnUrl,
    },
  });
}

// Server-to-server order status check - this, not anything the client
// submits, is what actually confirms a payment happened. Cashfree's
// checkout flow redirects the browser back to return_url rather than
// handing back a client-side signature the way Razorpay's popup does, so
// there's nothing to "verify" from the client at all - the order_id in
// the return URL is just a pointer to go ask Cashfree directly.
async function getOrder(orderId) {
  return cashfreeRequest('GET', `/orders/${encodeURIComponent(orderId)}`);
}

// Registers a shop as a Cashfree "vendor" - their bank account + minimal
// KYC. vendorId is generated by us (not returned by Cashfree), passed on
// every later call for that shop. verify_account: true triggers a
// penny-drop test transfer before the account is trusted, catching a
// mistyped account number before any real split payment relies on it.
async function createVendor({ vendorId, name, email, phone, bankAccountNumber, bankIfsc, bankAccountHolder, pan }) {
  return cashfreeRequest('POST', '/easy-split/vendors', {
    vendor_id: vendorId,
    status: 'ACTIVE',
    name,
    email,
    phone,
    verify_account: true,
    dashboard_access: false,
    schedule_option: 1, // Cashfree's default: T+1 settlement
    bank: {
      account_number: bankAccountNumber,
      account_holder: bankAccountHolder,
      ifsc: bankIfsc,
    },
    kyc_details: {
      account_type: 'INDIVIDUAL',
      pan,
    },
  });
}

async function getVendor(vendorId) {
  return cashfreeRequest('GET', `/easy-split/vendors/${encodeURIComponent(vendorId)}`);
}

// Attaches a split to an already-created order: `vendorAmount` (rupees)
// goes straight to that shop's bank account on Cashfree's normal
// settlement schedule (T+1 by default); whatever's left of order_amount
// automatically stays with this platform's own account - no separate call
// needed to claim the platform's share.
async function createOrderSplit({ orderId, vendorId, vendorAmount }) {
  return cashfreeRequest('POST', `/easy-split/orders/${encodeURIComponent(orderId)}/split`, {
    split: [{ vendor_id: vendorId, amount: vendorAmount }],
  });
}

// Verifies a webhook actually came from Cashfree before trusting its
// payload - the same "never trust an unverified callback" principle as
// Razorpay's payment signature (see razorpay.js). Cashfree signs
// `${timestamp}${rawBody}` with HMAC-SHA256 using the client secret,
// base64-encoded (unlike Razorpay's hex encoding) - see the file header
// for why this specific detail is worth double-checking against a real
// webhook delivery once sandbox access is available.
function verifyWebhookSignature({ rawBody, timestamp, signature }) {
  if (!CASHFREE_CLIENT_SECRET) {
    throw new Error('Cashfree is not configured - set CASHFREE_CLIENT_SECRET');
  }
  if (!rawBody || !timestamp || !signature) return false;

  const expected = crypto
    .createHmac('sha256', CASHFREE_CLIENT_SECRET)
    .update(timestamp + rawBody)
    .digest('base64');

  const expectedBuf = Buffer.from(expected, 'base64');
  const givenBuf = Buffer.from(String(signature), 'base64');
  if (expectedBuf.length !== givenBuf.length) return false;

  return crypto.timingSafeEqual(expectedBuf, givenBuf);
}

module.exports = {
  createOrder,
  getOrder,
  createVendor,
  getVendor,
  createOrderSplit,
  verifyWebhookSignature,
};
